### ISSUE TITLE
i want to Add stack and queue algorithm  

### ISSUE THREAD

**Issue by Mr-krishn** [sachinsingh3232/Hactoberfest#138]
hey i want to Add stack and queue algorithm  to your repo please assign the task to me

**Comment by Rohans-7** [comment]
Hey @sachinsingh3232 can you please assign this task to me. As it will be a great start way ahead for my open source journey. So please assign this to me.
Thank you.
Rohan

**Comment by Mr-krishn** [comment]
> Hey @sachinsingh3232 can you please assign this task to me. As it will be a great start way ahead for my open source journey. So please assign this to me. Thank you. Rohan

i have done this already
