### ISSUE TITLE
Add Fibonacci Number

### ISSUE THREAD

**Issue by BTANISHA11** [sachinsingh3232/Hactoberfest#14]
### Fibonacci number in C++
I want to add program to check whether a number is fibonacci number or not.
can you pls assign this to me @Sachinsingh2323

**Comment by mukulbaghel** [comment]
Hi I would like to do this problem ? 
Can u Assign me this issue ?

**Comment by Veeno-Rai** [comment]
@sachinsingh3232 
Please assign this to me!!

**Comment by manyadua16** [comment]
please assign this issue to me !

**Comment by AkanshuAich** [comment]
please assign me the issue sir

**Comment by Abhinav092003** [comment]
@sachinsingh3232 please assign this code to me because i know this code and wont be disappoint you..
please assign to me🙏🙏

**Comment by ayushrathore111** [comment]
Hii mam ,
I want to do this please this issue assign to me ...

**Comment by ShailjaPatil** [comment]
Hello there!
I would like to contribute in this issue , kindly assign it to me .
looking forward to your reply : )

**Comment by Vartika123456** [comment]
I will solve the problem by iterative and dp method. Please assign this issue to me.

**Comment by NiranjanLangade** [comment]
Hello,
Can you assign this issue to me please!!

**Comment by ChandniJha630** [comment]
I can solve this issue using dp approach in least time complexity. I can solve this issue. I would be highly obliged if you assign me this issue
